openapi: "3.0.0"
info:
  version: "Beta"
  title: VitalFrog Performance API
  contact: 
    email: support@vitalfrog.com
    name: VitalFrog support
  description: This is the very basic api spec of the new VitalFrog performance api
  termsOfService: https://www.vitalfrog.com/blog/terms
servers:
  - url: https://api.vitalfrog.com/v2
  - url: http://localhost:4444/v2
paths:
  /reports:
    post:
      summary: Create a new report
      description: sd
      tags:
        - performance reports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNewReportBody'
      responses:
        '202':
          description: New async report started. Runs async. Status can be fetched via uuid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AsyncReport"
        '200':
          description: New sync report created. Diretly returns report. May run for long time
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SyncReport"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /reports/{uuid}:
    get:
      security: []
      summary: Get a all data of a single report
      description: sd
      parameters:
        - in: path
          name: uuid
          description: asd
          required: true
          schema:
            type: string
          example: 1dea0c0e-e1e0-11ec-8fea-0242ac120002
      tags:
        - performance reports
      responses:
        '200':
          description: Single performance report
          content:
            application/json:
             schema:
               $ref: "#/components/schemas/SyncReport"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /performance_budgets:
    get:
      summary: List all available performance budgets for this account
      description: sd
      tags:
        - performance budgets
      responses:
        '200':
          description: List of all performance budgets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PerformanceBudgetsList"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  
  /performance_budgets/{id}:
    get:
      summary: Get single performance budget
      description: sd
      parameters:
        - in: path
          name: id
          description: asd
          required: true
          schema:
            type: integer
            format: int32
          example: 1
      tags:
        - performance budgets
      responses:
        '200':
          description: Performance budgets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PerformanceBudgets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    APIToken:    
      type: http
      scheme: bearer
      bearerFormat: "firebaseAccessToken"
  schemas:
    CreateNewReportBody:
      type: object
      required:
        - config
        - async
        - jsonl
      properties:
        config:
          $ref: "#/components/schemas/ReportConfig"
        async:
          type: boolean
          description: Run the report async and directly return with a 202
        jsonl:
          type: boolean
          description: Return the response as jsonl. Allows to shwo results already while run is not finished. Only works for sync report
    SyncReport: 
      type: object
      required:
        - metadata
        - data
      properties:
        metadata: 
          $ref: "#/components/schemas/ReportMetadata"
        data:
          type: array
          items:
            $ref: "#/components/schemas/PerformanceReport"
    AsyncReport: 
      type: object
      required:
        - metadata
      properties:
        metadata: 
          $ref: "#/components/schemas/ReportMetadata"
    Countries:
      type: object
      required:
        - list
        - mode
      properties:
        mode:
          type: string
          description: How to handle the 'list'. If 'allow_list' than new countries is allowed, but the ones on the list. If 'block_list' then all countries are allowd.
          default: block_list
          enum:
            - block_list
            - allow_list
        list:
          type: array
          items:
            $ref: "#/components/schemas/Country"
    Target:
      type: object
      required:
        - host
        - paths
      properties:
        host: 
          type: string
          example: www.vitalfrog.com
        scheme:
          type: string
          example: https
          default: https
        paths:
          type: object
          anyOf:
            - $ref: "#/components/schemas/ManualPathSelection" 
    Header:
      type: object
      required:
        - header
        - value
      properties:
        header:
          type: string
        value:
          type: string
    ExtraHeadersConfig:
      type: array
      description: Additional headers to configure on the request. Mostly used for authentication
      items:
        $ref: "#/components/schemas/Header"
    BasicAuth:
      type: object
      description: Basic auth credentials to configure
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string 
    HttpConfig:
      type: object
      description: Additional http request configurations
      properties:
        extra_headers:
          $ref: "#/components/schemas/ExtraHeadersConfig"
        basic_auth:
          $ref: "#/components/schemas/BasicAuth"
    ReportConfig: 
      type: object
      required:
        - target
      properties:
        countries: 
          $ref: "#/components/schemas/Countries"
        performance_budgets_id:
          description: What performance budget to use. If none configured the default VitalFrog performance budgets will be used
          type: integer
          format: int32
          example: 1
        devices:
          type: array
          description: What devices to test. If not set falls back to testing two devices "desktop" & "mobile"
          items: 
            $ref: "#/components/schemas/Device"
        target: 
          $ref: "#/components/schemas/Target"
        http:
          $ref: "#/components/schemas/HttpConfig"
    AllPaths:
      type: object
      description: VitalFrog will crawl all paths it can find and run performance report on it
      required:
        - mode
      properties:
        mode:
          type: string
          pattern: '^allPaths$'
    RandomPathSelection:
      type: object
      description: VitalFrog will select a random sample of paths it can find and run performance report on it
      required:
        - mode
        - count
      properties:
        mode:
          type: string
          pattern: '^randomSelection$'
        count:
          type: integer
          default: 10
          description: How many paths to maximum crawl. If -1 this is equal to "allPaths" mode
    ManualPathSelection:
      type: object
      description: VitalFrog will run performance report on the manual configured paths
      required:
        - mode
        - paths
      properties:
        mode:
          type: string
          pattern: '^manual$'
        paths:
          type: array
          items:
            type: string
            pattern: "^/.*$"
    Device:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          enum:
            - desktop
            - mobile
    PerformanceBudgetsList:
      type: array
      items:
        $ref: "#/components/schemas/PerformanceBudgets"
    PerformanceBudgets:
      type: object
      required:
        - id
        - budgets
        - description
        - default
      properties:
        id:
          type: integer
          format: int32
          example: 1
        description:
          type: string
          example: Default VitalFrog performance budget
        default:
          type: boolean
          description: Flags if this performance budget is the default one to use for this account
        budgets:
          type: array
          items: 
            $ref: "#/components/schemas/PerformanceBudget"
    PerformanceBudget:
      type: object
      required:
        - metric
        - error
        - warning
      properties:
        metric:
          type: string
          enum: 
            - first_contentful_paint_ms
            - largest_contentful_paint_ms
            - first_meaningful_paint_ms
            - speed_index_ms
            - total_blocking_time_ms
            - max_potential_fid_ms
            - cumulative_layout_shift
            - server_response_time_ms
            - interactive_ms
            - big_payloads.total_bytes
        mode:
          description: What to alert on. Above or below the threshold
          type: string
          default: "above"
          enum:
            - "above"
            - "below"
        warning:
          type: integer
          format: int32
          description: If metric is above/below (depending on 'mode'). Return a warning
        error:
          type: integer
          format: int32
          description: If metric is above/below (depending on 'mode'). Return an error 
    ReportMetadata:
      type: object
      required:
        - uuid
        - created
        - config
        - cost
      properties:
        uuid:
          type: string
          example: 1dea0c0e-e1e0-11ec-8fea-0242ac120002
        created:
          type: string
          format: date-time
        cost: 
          type: integer
          format: int32
          description: Cost in credits for this report
        config: 
          $ref: "#/components/schemas/ReportConfig"
    Country:
      type: object
      required:
        - code
      properties:
        name:
          type: string
          example: "Germany"
        code:
          type: string
          example: "DE"
    Error:
      type: object
      required:
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Element:
      type: object
      required:
        - selector
        - snipper
      properties:
        selector:
          type: string
          example: div#particlesJS > div.max-w-screen-xl > div.text-center > p.text-xl
        snippet: 
          type: string
          example: <p class=text-xl text-gray-600 xl:text-2xl mb-4>
    NetworkRequest: 
      type: object
      required:
        - url
        - size_byte
        - start_time_ms
        - load_time_ms
      properties:
        url: 
          type: string
          example: https://www.vitalfrog.com/
        size_byte: 
          type: integer
          format: int32
          example: 16202
        start_time_ms: 
          type: integer
          format: int32
          example: 0
        load_time_ms: 
          type: integer
          format: int32
          example: 131
    Payload:
      type: object
      required:
        - url
        - total_bytes
      properties: 
        url: 
          type: string
          example: https://www.vitalfrog.com/images/road.jpg
        total_bytes: 
          type: integer
          format: int32
          example: 1027876
    LargestContentfulPaint:
      type: object
      required:
        - value_ms
        - element
      properties: 
        value_ms: 
          type: integer
          format: int32
          example: 3124
        element: 
          $ref: "#/components/schemas/Element"
        lazy_loaded: 
          type: boolean
        image_preloaded: 
          type: boolean
    FirstContentfulPaint:
      type: object
      required:
        - value_ms
      properties: 
        value_ms: 
          type: integer
          format: int32
          example: 937
        elements:
          type: array
          items:
            $ref: "#/components/schemas/Element"
    CumulativeLayoutShift:
      type: object
      required:
        - value
      properties: 
        value: 
          type: number
          format: float
          example: 0.1
        elements:
          type: array
          items:
            $ref: "#/components/schemas/Element"
    BigPayloads:
      type: object
      required:
        - total_bytes
        - payloads
      properties: 
        total_bytes: 
          type: integer
          format: int32
          example: 2802127
        payloads: 
          type: array
          items: 
            $ref: "#/components/schemas/Payload"
    PerformanceReport: 
      type: object
      required:
        - path
        - country
        - device
        - first_contentful_paint
        - cumulative_layout_shift
        - largest_contentful_paint
        - first_meaningful_paint_ms
        - speed_index_ms
        - total_blocking_time_ms
        - max_potential_fid_ms
        - server_response_time_ms
        - interactive_ms
        - network_requests
        - big_payloads
      properties: 
        path: 
          type: string
          example: /blog
        country:
          $ref: "#/components/schemas/Country"
        device:
          $ref: "#/components/schemas/Device"
        first_contentful_paint: 
          $ref: "#/components/schemas/FirstContentfulPaint"
        largest_contentful_paint: 
          $ref: "#/components/schemas/LargestContentfulPaint"
        first_meaningful_paint_ms: 
          type: integer
          format: int32
          example: 2195
        speed_index_ms: 
          type: integer
          format: int32
          example: 937
        total_blocking_time_ms: 
          type: integer
          format: int32
          example: 0
        max_potential_fid_ms: 
          type: integer
          format: int32
          example: 16
        cumulative_layout_shift: 
          $ref: "#/components/schemas/CumulativeLayoutShift"
        server_response_time_ms: 
          type: integer
          format: int32
          example: 86
        interactive_ms: 
          type: integer
          format: int32
          example: 2195
        network_requests: 
          type: array
          items: 
            $ref: "#/components/schemas/NetworkRequest"
        big_payloads: 
          $ref: "#/components/schemas/BigPayloads"
security:
  - APIToken: []         # use the same name as above