
name: Deploy to GitHub pages

# Controls when the action will run.
# In this case, when changes are made to the source branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - run: |
        cp ./openapi.yml ./redoc/openapi.yml
    # Installs dependencies and generates static files inside the wwwroot folder
    - name: Generate static files in wwwroot
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: |
        cd redoc
        npx redoc-cli build -t redocTemplate.hbs --disableGoogleFont -o api-spec.html openapi.yml

    # Copy extra files to the wwwroot folder
    - run: |
        cp ./openapi.yml ./docs/openapi.yml
        cp ./redoc/api-spec.html ./docs/api-spec.html
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}